In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/Book3.csv')
df

,attendence,Unnamed: 1,practical submission,Unnamed: 3,Unnamed: 4,internal marks,Unnamed: 6,sgpa>9
0,average,NaN,average,NaN,NaN,average,NaN,no
1,excellent,NaN,average,NaN,NaN,poor,NaN,yes
2,average,NaN,poor,NaN,NaN,average,NaN,no
3,poor,NaN,execllent,NaN,NaN,excellent,NaN,yes
4,poor,NaN,poor,NaN,NaN,poor,NaN,yes
5,average,NaN,average,NaN,NaN,average,NaN,yes
6,excellent,NaN,excellent,NaN,NaN,poor,NaN,no
7,poor,NaN,average,NaN,NaN,average,NaN,no
8,average,NaN,excellent,NaN,NaN,excellent,NaN,yes
9,poor,NaN,poor,NaN,NaN,poor,NaN,yes
10,average,NaN,average,NaN,NaN,average,NaN,no

In [ ]:
inputs = df.drop('sgpa>9',axis='columns')

In [ ]:
target = df['sgpa>9']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_attendence = LabelEncoder()
le_practical_submission = LabelEncoder()
le_internal_marks= LabelEncoder()

In [ ]:
inputs['attendence_n'] = le_attendence.fit_transform(inputs['attendence'])
inputs['practical_submission_n'] = le_practical_submission.fit_transform(inputs['practical submission'])
inputs['internal_marks_n'] = le_internal_marks.fit_transform(inputs['internal marks'])

In [ ]:
inputs

,attendence,Unnamed: 1,practical submission,Unnamed: 3,Unnamed: 4,internal marks,Unnamed: 6,attendence_n,practical_submission_n,internal_marks_n
0,average,NaN,average,NaN,NaN,average,NaN,0,0,0
1,excellent,NaN,average,NaN,NaN,poor,NaN,1,0,2
2,average,NaN,poor,NaN,NaN,average,NaN,0,3,0
3,poor,NaN,execllent,NaN,NaN,excellent,NaN,2,2,1
4,poor,NaN,poor,NaN,NaN,poor,NaN,2,3,2
5,average,NaN,average,NaN,NaN,average,NaN,0,0,0
6,excellent,NaN,excellent,NaN,NaN,poor,NaN,1,1,2
7,poor,NaN,average,NaN,NaN,average,NaN,2,0,0
8,average,NaN,excellent,NaN,NaN,excellent,NaN,0,1,1
9,poor,NaN,poor,NaN,NaN,poor,NaN,2,3,2
10,average,NaN,average,NaN,NaN,average,NaN,0,0,0

In [ ]:
inputs_n = inputs.drop(['attendence','practical submission','internal marks'],axis='columns')

In [ ]:
inputs_n

,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 6,attendence_n,practical_submission_n,internal_marks_n
0,NaN,NaN,NaN,NaN,0,0,0
1,NaN,NaN,NaN,NaN,1,0,2
2,NaN,NaN,NaN,NaN,0,3,0
3,NaN,NaN,NaN,NaN,2,2,1
4,NaN,NaN,NaN,NaN,2,3,2
5,NaN,NaN,NaN,NaN,0,0,0
6,NaN,NaN,NaN,NaN,1,1,2
7,NaN,NaN,NaN,NaN,2,0,0
8,NaN,NaN,NaN,NaN,0,1,1
9,NaN,NaN,NaN,NaN,2,3,2
10,NaN,NaN,NaN,NaN,0,0,0

,Unnamed: 1,Unnamed: 3,Unnamed: 4,Unnamed: 6,attendence_n,practical_submission_n,internal_marks_n
0,NaN,NaN,NaN,NaN,0,0,0
1,NaN,NaN,NaN,NaN,1,0,2
2,NaN,NaN,NaN,NaN,0,3,0
3,NaN,NaN,NaN,NaN,2,2,1
4,NaN,NaN,NaN,NaN,2,3,2
5,NaN,NaN,NaN,NaN,0,0,0
6,NaN,NaN,NaN,NaN,1,1,2
7,NaN,NaN,NaN,NaN,2,0,0
8,NaN,NaN,NaN,NaN,0,1,1
9,NaN,NaN,NaN,NaN,2,3,2
10,NaN,NaN,NaN,NaN,0,0,0

In [ ]:
target

0      no
1     yes
2      no
3     yes
4     yes
5     yes
6      no
7      no
8     yes
9     yes
10     no
Name: sgpa>9, dtype: object

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [ ]:
model.fit(inputs_n, target)

DecisionTreeClassifier()

In [ ]:
model.score(inputs_n,target)

0.9090909090909091

In [ ]:
import pandas as pd

### Ensure Google Drive is mounted and the CSV file path is correct.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# Make sure 'Book3.csv' exists at this path in your Google Drive
df=pd.read_csv('/content/drive/MyDrive/Book3.csv')

Mounted at /content/drive

In [ ]:
inputs = df.drop('sgpa>9',axis='columns')
target = df['sgpa>9']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le_attendence = LabelEncoder()
le_practical_submission = LabelEncoder()
le_internal_marks= LabelEncoder()

In [ ]:
inputs['attendence_n'] = le_attendence.fit_transform(inputs['attendence'])
inputs['practical_submission_n'] = le_practical_submission.fit_transform(inputs['practical submission'])
inputs['internal_marks_n'] = le_internal_marks.fit_transform(inputs['internal marks'])

In [ ]:
inputs_n = inputs[['attendence_n', 'practical_submission_n', 'internal_marks_n']]

### Defining and Fitting the Decision Tree Model

In [ ]:
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [ ]:
model.fit(inputs_n, target)
print('Model re-fitted successfully with 3 features!')

Model re-fitted successfully with 3 features!

In [ ]:
print(f'Prediction for [[2,1,0]]: {model.predict([[2,1,0]])}')

Prediction for [[2,1,0]]: ['no']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

In [ ]:
model.score(inputs_n,target)

0.9090909090909091